### ISSUE TITLE
Testen des Gameplay-Parsers

### ISSUE THREAD

**Issue by JOOpdenhoevel** [JOOpdenhoevel/EngineL#7]
Der Gameplay-Parser ist von essentieller Bedeutung für EngineL, da er die Interaktion des Spielers mit dem Spiel überhaupt erst ermöglicht. Da dieser noch ungetestet ist, muss ein automatischer Test erstellt werden.

Die Tests laufen alle nach dem gleichen Muster ab: Über die API wird der Text der Eingabezeile gesetzt und die Methode `command_entered` des GameplayParsers aufgerufen. Anschließend wird untersucht, ob der Befehl das gewünschte Ergebnis hatte.

Folgende Befehle sollen untersucht werden:
* "" (ein leerer String): Nichts soll passieren.
* "den dir zu an ab um dich hin": Nichts soll passieren, da das alle Wörter sind, die vom Parser gefiltert werden.
* "sieh": Im Textfeld erscheint die komplette Beschreibung des aktuellen Ortes des Spielers.
* "sieh zum Ort": Siehe oben.
* "sieh zur Tasche": Im Textfeld erscheint die Inventarauflistung des Spielers.
* "sieh zur Bar" ("Bar" ist ein Gegenstand im gleichen Raum): Im Textfeld erscheint die Beschreibung der Bar.
* "gehe zum Hafen" ("Hafen" ist ein Ort, der mit dem aktuellen Ort des Spielers verbunden ist): Das Spieler-Entity transferiert sich zum Hafen.
* "nimm Fisch" ("Fisch" ist ein Gegenstand im Hafen): Der Spieler transferiert den Fisch auf sich selbst.
* "leg Fisch": Der Spieler transferiert den Fisch wieder auf den Hafen.
* "sprich den Fisch an": Die `on_talk_to`-Methode des Fisches wird aufgerufen.
* "kombiniere Fisch mit Brötchen" ("Brötchen" ist ein Gegenstand im Hafen, der mit "Fisch" kombinierbar ist): Fisch und Brötchen werden zu `None` transferiert und ein Fischbrötchen wird erstellt.
* "benutze Fischbrötchen": Das Fischbrötchen wird zu `None` transferiert.

**Comment by Janonard** [comment]
Da in diesem Test sehr viel mit Befehlen gearbeitet wird, kann anschließend auch die Befehlssuche getestet werden: Dafür muss, nachdem der oben genannte Test abgeschlossen ist, der `CommandLine` des Spieler-Fensters ein Event mit den entsprechenden Tastendrücken geschickt und anschließend der Text in der `CommandLine` abgfragt werden. Im genauen soll der Test wie folgend ablaufen:

* (Oben): Die Eingabezeile hat den Text "benutze Fischbrötchen"
* (Oben): Die Eingabezeile hat den Text "kombiniere Fisch mit Brötchen"
* (Unten): Die Eingabezeile hat den Text "benutze Fischbrötchen"
* (Unten): Die Eingabezeile hat den Text ""
